-- AlterTable
ALTER TABLE "Site" ALTER COLUMN "endDate" DROP NOT NULL,
ALTER COLUMN "endDate" DROP DEFAULT,
ALTER COLUMN "startDate" DROP NOT NULL,
ALTER COLUMN "startDate" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SiteDayOff" ALTER COLUMN "workDate" DROP DEFAULT;
